"""initial schema

Revision ID: 3bbfe6f6abf7
Revises: 
Create Date: 2026-10-05 20:46:02.241581
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3bbfe6f6abf7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_api_cache'))
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_az', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('api_id', name=op.f('uq_leagues_api_id'))
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_runs_run_date'), ['run_date'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_notifications_dedup_key'))
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('elo', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('api_id', name=op.f('uq_teams_api_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_users_telegram_chat_id'))
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(length=80), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('ht_home_goals', sa.Integer(), nullable=True),
    sa.Column('ht_away_goals', sa.Integer(), nullable=True),
    sa.Column('referee', sa.String(length=120), nullable=True),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('details_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('history_checked_at', sa.DateTime(), nullable=True),
    sa.Column('h2h_checked_at', sa.DateTime(), nullable=True),
    sa.Column('injuries_checked_at', sa.DateTime(), nullable=True),
    sa.Column('odds_checked_at', sa.DateTime(), nullable=True),
    sa.Column('lineups_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_matches_league_id_leagues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('api_id', name=op.f('uq_matches_api_id'))
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_is_priority'), ['is_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_kickoff_utc'), ['kickoff_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_league_id'), ['league_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('role_tags', sa.JSON(), nullable=False),
    sa.Column('minutes_share', sa.Double(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('api_id', name=op.f('uq_players_api_id'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('drawn', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goal_diff', sa.Integer(), nullable=True),
    sa.Column('form', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('home', sa.JSON(), nullable=False),
    sa.Column('away', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_standings_league_id_leagues')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_standings_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings')),
    sa.UniqueConstraint('league_id', 'season', 'team_id', 'group_name', name=op.f('uq_standings_league_id_season_team_id_group_name'))
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_team_id'), ['team_id'], unique=False)

    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Double(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_ratings_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_ratings')),
    sa.UniqueConstraint('team_id', 'as_of', 'source', name=op.f('uq_team_ratings_team_id_as_of_source'))
    )
    with op.batch_alter_table('team_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_ratings_team_id'), ['team_id'], unique=False)

    op.create_table('analysis_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Double(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_analysis_logs_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_logs'))
    )
    with op.batch_alter_table('analysis_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_logs_match_id'), ['match_id'], unique=False)

    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('api_type', sa.String(length=40), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_injuries_match_id_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_injuries_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_injuries_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injuries')),
    sa.UniqueConstraint('match_id', 'player_id', name=op.f('uq_injuries_match_id_player_id'))
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_team_id'), ['team_id'], unique=False)

    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('coach', sa.String(length=120), nullable=True),
    sa.Column('starters', sa.JSON(), nullable=False),
    sa.Column('substitutes', sa.JSON(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_lineups_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_lineups_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineups')),
    sa.UniqueConstraint('match_id', 'team_id', name=op.f('uq_lineups_match_id_team_id'))
    )
    with op.batch_alter_table('lineups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lineups_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lineups_team_id'), ['team_id'], unique=False)

    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shots_off_target', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('shots_inside_box', sa.Integer(), nullable=True),
    sa.Column('shots_outside_box', sa.Integer(), nullable=True),
    sa.Column('possession', sa.Double(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy', sa.Double(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('xg', sa.Double(), nullable=True),
    sa.Column('xg_source', sa.String(length=16), nullable=True),
    sa.Column('big_chances', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_stats_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_stats_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_stats')),
    sa.UniqueConstraint('match_id', 'team_id', name=op.f('uq_match_stats_match_id_team_id'))
    )
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_stats_team_id'), ['team_id'], unique=False)

    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('bookmaker_api_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker', sa.String(length=80), nullable=False),
    sa.Column('market', sa.String(length=24), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Double(), nullable=True),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_odds_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds'))
    )
    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.create_index('ix_odds_lookup', ['match_id', 'market', 'selection', 'line', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_match_id'), ['match_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=24), nullable=False),
    sa.Column('selection', sa.String(length=16), nullable=False),
    sa.Column('line', sa.Double(), nullable=True),
    sa.Column('model_prob', sa.Double(), nullable=True),
    sa.Column('market_prob', sa.Double(), nullable=True),
    sa.Column('final_prob', sa.Double(), nullable=True),
    sa.Column('fair_odds', sa.Double(), nullable=True),
    sa.Column('best_odds', sa.Double(), nullable=True),
    sa.Column('bookmaker', sa.String(length=80), nullable=True),
    sa.Column('edge_pp', sa.Double(), nullable=True),
    sa.Column('ev', sa.Double(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('llm_summary', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_match_id'), ['match_id'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('ht_home_goals', sa.Integer(), nullable=True),
    sa.Column('ht_away_goals', sa.Integer(), nullable=True),
    sa.Column('total_corners', sa.Integer(), nullable=True),
    sa.Column('total_cards', sa.Integer(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_results_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results')),
    sa.UniqueConstraint('match_id', name=op.f('uq_results_match_id'))
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('stake', sa.Double(), nullable=False),
    sa.Column('odds_taken', sa.Double(), nullable=False),
    sa.Column('odds_closing', sa.Double(), nullable=True),
    sa.Column('clv', sa.Double(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('pnl', sa.Double(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_bets_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bets'))
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('pyramid_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('stage_no', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Double(), nullable=False),
    sa.Column('odds', sa.Double(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Double(), nullable=True),
    sa.Column('locked_amount', sa.Double(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], name=op.f('fk_pyramid_stages_bet_id_bets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pyramid_stages'))
    )
    with op.batch_alter_table('pyramid_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyramid_stages_attempt_no'), ['attempt_no'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyramid_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyramid_stages_attempt_no'))

    op.drop_table('pyramid_stages')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_prediction_id'))

    op.drop_table('bets')
    op.drop_table('results')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_match_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('odds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odds_match_id'))
        batch_op.drop_index('ix_odds_lookup')

    op.drop_table('odds')
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_match_stats_match_id'))

    op.drop_table('match_stats')
    with op.batch_alter_table('lineups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lineups_team_id'))
        batch_op.drop_index(batch_op.f('ix_lineups_match_id'))

    op.drop_table('lineups')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_team_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_player_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_match_id'))

    op.drop_table('injuries')
    with op.batch_alter_table('analysis_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_logs_match_id'))

    op.drop_table('analysis_logs')
    with op.batch_alter_table('team_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_ratings_team_id'))

    op.drop_table('team_ratings')
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_team_id'))
        batch_op.drop_index(batch_op.f('ix_standings_league_id'))

    op.drop_table('standings')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))

    op.drop_table('players')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_league_id'))
        batch_op.drop_index(batch_op.f('ix_matches_kickoff_utc'))
        batch_op.drop_index(batch_op.f('ix_matches_is_priority'))
        batch_op.drop_index(batch_op.f('ix_matches_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_matches_away_team_id'))

    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('notifications')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_run_date'))
        batch_op.drop_index(batch_op.f('ix_model_runs_kind'))

    op.drop_table('model_runs')
    op.drop_table('leagues')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
