"""price checks

Revision ID: 67abb2e58b1b
Revises: c8898af63233
Create Date: 2026-10-06 17:04:48.735690
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '67abb2e58b1b'
down_revision: str | None = 'c8898af63233'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=40), nullable=False),
    sa.Column('odds', sa.Double(), nullable=False),
    sa.Column('min_odds', sa.Double(), nullable=True),
    sa.Column('best_odds', sa.Double(), nullable=True),
    sa.Column('p_final', sa.Double(), nullable=True),
    sa.Column('ev', sa.Double(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_price_checks_match_id_matches')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_price_checks_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_checks'))
    )
    with op.batch_alter_table('price_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_checks_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_checks_prediction_id'), ['prediction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_checks_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_price_checks_match_id'))

    op.drop_table('price_checks')
    # ### end Alembic commands ###
