"""free data sources

Revision ID: c8898af63233
Revises: 00b86a8dca43
Create Date: 2026-10-06 10:34:42.075331
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c8898af63233'
down_revision: str | None = '00b86a8dca43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_scorers_league_id_leagues')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_scorers_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scorers')),
    sa.UniqueConstraint('league_id', 'season', 'team_id', 'player_name', name=op.f('uq_scorers_league_id_season_team_id_player_name'))
    )
    with op.batch_alter_table('scorers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scorers_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scorers_team_id'), ['team_id'], unique=False)

    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_aliases_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_aliases')),
    sa.UniqueConstraint('source', 'key', name=op.f('uq_team_aliases_source_key'))
    )
    with op.batch_alter_table('team_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_aliases_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_results', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=24), nullable=False, server_default='api_football'))
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=True))
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_matches_source_external_id'), ['source', 'external_id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_matches_source_external_id'), type_='unique')
        batch_op.alter_column('api_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('external_id')
        batch_op.drop_column('source')

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('full_results')

    with op.batch_alter_table('team_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_aliases_team_id'))

    op.drop_table('team_aliases')
    with op.batch_alter_table('scorers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scorers_team_id'))
        batch_op.drop_index(batch_op.f('ix_scorers_league_id'))

    op.drop_table('scorers')
    # ### end Alembic commands ###
